[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

[rpc_endpoints]
sonic = "https://rpc.soniclabs.com"

[etherscan]
sonic = { key = "${SONICSCAN_API_KEY}", url = "https://api.sonicscan.org/api", chain = 146 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options